#db.url=jdbc:mysql://127.0.0.1:3306/greenmart?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#db.username=greenmart
#db.password=greenmart
#db.driver=com.mysql.cj.jdbc.Driver
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true


db.url=jdbc:h2:file:../data/greenmart;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
db.driver=org.h2.Driver
db.username=sa
db.password=
hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
hibernate.globally_quoted_identifiers=true